import type { GameMode } from '@/types';

export const GAME_MODES: GameMode[] = [
  {
    id: 'country-flags',
    title: 'World',
    description: 'Identify flags from all 197 countries. How long can your streak go?',
    flagCode: 'earth',
    flagImageUrl: 'https://images.squarespace-cdn.com/content/v1/5fa6b76b045ef433ae7b252e/1604765875569-MUAEJNXG2NL6E4VEORZ6/Flag_20x30.jpg',
    available: true,
    section: 'world',
  },
  {
    id: 'africa-flags',
    title: 'Africa',
    description: 'Identify all 54 African country flags. Can you name them all?',
    flagCode: 'za',
    available: true,
    section: 'world',
  },
  {
    id: 'north-america-flags',
    title: 'North America',
    description: 'Identify flags from all 23 North American countries.',
    flagCode: 'mx',
    available: true,
    section: 'world',
  },
  {
    id: 'south-america-flags',
    title: 'South America',
    description: 'Identify flags from all 12 South American countries.',
    flagCode: 'br',
    available: true,
    section: 'world',
  },
  {
    id: 'asia-flags',
    title: 'Asia',
    description: 'Identify flags from all 49 Asian countries.',
    flagCode: 'cn',
    available: true,
    section: 'world',
  },
  {
    id: 'europe-flags',
    title: 'Europe',
    description: 'Identify flags from all 45 European countries.',
    flagCode: 'eu',
    available: true,
    section: 'world',
  },
  {
    id: 'oceania-flags',
    title: 'Oceania',
    description: 'Identify flags from all 14 Oceanian countries.',
    flagCode: 'au',
    available: true,
    section: 'world',
  },
  {
    id: 'us-state-flags',
    title: 'US States',
    description: 'Identify all 50 American state flags. Can you name them all?',
    flagCode: 'us',
    available: true,
    section: 'subdivisions',
  },
  {
    id: 'ca-province-flags',
    title: 'Canadian Provinces',
    description: 'Identify all 13 Canadian provinces and territories by their flag.',
    flagCode: 'ca',
    available: true,
    section: 'subdivisions',
  },
  {
    id: 'one-piece-flags',
    title: 'One Piece',
    description: 'Identify Jolly Rogers from 39 One Piece pirate crews and organizations.',
    flagCode: 'op',
    flagImageUrl: '/images/pirate-crews/op-strawhats.png',
    available: true,
    section: 'general',
  },
  {
    id: 'nba-logos',
    title: 'NBA',
    description: 'Identify all 30 NBA team logos. How many do you know?',
    flagCode: 'nba',
    flagImageUrl: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/leagues/500/nba.png&transparent=true',
    available: true,
    section: 'sports',
    answerMode: 'text-input',
  },
  {
    id: 'nhl-logos',
    title: 'NHL',
    description: 'Identify all 32 NHL team logos. Can you name them all?',
    flagCode: 'nhl',
    flagImageUrl: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/leagues/500/nhl.png&transparent=true',
    available: true,
    section: 'sports',
    answerMode: 'text-input',
  },
  {
    id: 'mlb-logos',
    title: 'MLB',
    description: 'Identify all 30 MLB team logos. How well do you know baseball?',
    flagCode: 'mlb',
    flagImageUrl: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/leagues/500/mlb.png&transparent=true',
    available: true,
    section: 'sports',
    answerMode: 'text-input',
  },
  {
    id: 'nfl-logos',
    title: 'NFL',
    description: 'Identify all 32 NFL team logos. How many can you name?',
    flagCode: 'nfl',
    flagImageUrl: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/leagues/500/nfl.png&transparent=true',
    available: true,
    section: 'sports',
    answerMode: 'text-input',
  },
  {
    id: 'capital-quiz',
    title: 'Capital Quiz',
    description: 'See a flag — name the capital city.',
    flagCode: 'fr',
    available: true,
    section: 'general',
  },
];
